### ISSUE TITLE
Volume is boundless

### ISSUE THREAD

**Issue by kgraves** [ChicoTeam/pianobar#11]
Link to original bug report: https://github.com/PromyLOPh/pianobar/issues/150

Volume seems to go up to 11, causing distortion... well more like 10000%. The issue is that you never know if the volume is at 100%, specially when you listen to electronica.

I'll look into this and get back to you, I might just fix it my self.

**Comment by oulrich1** [comment]
what would be nice at least is volume indicator. Maybe in % format  or  currentvolume:MAXvolume format.

**Comment by oulrich1** [comment]
Hey Kyle! I completely forgot about this project. Until just now. This was a pretty neat music player.

**Comment by kgraves** [comment]
Hey Oriah! Sorry for the late response. Yeah, it was an awesome player. I wish something like this existed for spotify, that would be awesome.
