### ISSUE TITLE
Commands exist that aren't in the list of commands

### ISSUE THREAD

**Issue by kgraves** [ChicoTeam/pianobar#18]
I went to 'love' a song and instead of hitting Shift-+, I accidentally hit Ctrl-+ and it was asking if I wanted to remove feedback for the current song or something else about the song (possibly remove it from the station or something).

We should get some of these documented and put into the list of commands that prints

**Comment by oulrich1** [comment]
There is no Ctrl - + command. If you press Ctrl - + it is the same as just pressing '='.  = is the command to "Fetch station info" and it brings up the options to delete artists seeds or feedback. I don't believe that it is a hidden command. 

However  i just noticed that when this command ('=') was pressed, and the command is not closed (by pressing "enter", or "f" or "a"), the next song does not start playing after the last song finishes. Only after closing the menu (pressing enter) did the next song start to play.
