### ISSUE TITLE
Features not listed here yet

### ISSUE THREAD

**Issue by russplaysguitar** [ChicoTeam/pianobar#3]
Please copy existing feature requests from https://github.com/PromyLOPh/pianobar and list any new ones you can think of.

**Comment by ghost** [comment]
1. Titlebar changes with song

cmus does this: http://cmus.sourceforge.net/

Here is how cmus does it:
(file: ui_curses.c line 1255)

static void set_title(const char *title)
{
        if (!set_term_title)
                return;

```
    if (t_ts) {
            printf("%s%s%s", tgoto(t_ts, 0, 0), title, t_fs);
            fflush(stdout);
    }
```

}
Other possibly useful info: http://www.ibiblio.org/pub/Linux/docs/HOWTO/Xterm-Title

Workaround: echo -e "format_nowplaying_song = \033]2;%t by %a\007" >> config
1. Shuffle stations

Given that pandora's quickmix is seems to be the only (and somewhat cumbersome) way of shuffling stations, it seems it would be straightforward to build arbitrarily feature-rich shuffling in on the client side.

**Comment by russplaysguitar** [comment]
Can you post "Titlebar changes with song" and "Shuffle stations" as separate issues? This thread was intended mainly to remind you to post some issues.

**Comment by russplaysguitar** [comment]
Thanks Arpit!
